# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-02 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181002_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified_at',
            field=models.DateField(),
        ),
    ]
