# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-03 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181002_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/headers'),
        ),
    ]
