# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-10 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181010_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='appeareances',
            new_name='appearances',
        ),
    ]
