# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181010_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='active-years',
            field=models.IntegerField(default=0, verbose_name='Years active'),
        ),
    ]
