# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-10 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_card_active-years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='active-years',
            new_name='active',
        ),
    ]
