# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181010_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Number of openings'),
        ),
    ]
